#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.3.1}
LITE=${3:-}

curl -s https://raw.githubusercontent.com/mage2click/docker-magento-mutagen/version/1.1.0-varnish/lib/template|bash -s - magento-2
bin/download $VERSION

while grep -qw "$DOMAIN" /etc/hosts || [ -z "$DOMAIN" ]; do
    if [ -z "$DOMAIN" ]; then
        echo "Domain cannot be empty!"
        RES='y'
    else
        read -p "Domain $DOMAIN is already exists in /etc/hosts, use another? [y/n]: " RES
    fi

    if [[ $RES =~ ^[Yy]$ ]]; then
        read -p "New domain: " DOMAIN
        RES=''
    else
        break
    fi
done

if ! grep -qw "$DOMAIN" /etc/hosts; then
    echo "Your system password has been requested to add an entry to /etc/hosts..."
    echo "127.0.0.1 $DOMAIN" | sudo tee -a /etc/hosts
fi

if [ -z "$LITE" ]; then
    bin/setup $DOMAIN
else
    bin/setup-lite $DOMAIN
fi
