#!/bin/bash
git init -qqq
git remote add origin https://github.com/mage2click/docker-magento
git fetch origin -qqq
git checkout origin/develop -- compose/$1
mv compose/$1/* ./
mv compose/$1/.vscode ./
rm -rf compose .git
git init
